{"uid":"4b81908effdddaf6","name":"test_github","fullName":"tests.test_selene#test_github","historyId":"5167f7c71535600a353c42dca9c39857","time":{"start":1697444620037,"stop":1697444620038,"duration":1},"status":"broken","statusMessage":"ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/webdriver_manager/core/utils.py)","statusTrace":"browser_management = None\n\n    def test_github(browser_management):\n>       browser.open('/')\n\ntests/test_selene.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py:1154: in open\n    self.config._executor.get_url(relative_or_absolute_url)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:303: in get_url\n    self.config._driver_get_url_strategy(self.config)(url)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:218: in get\n    driver = config.driver\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:345: in __get__\n    driver = config.build_driver_strategy(config)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nconfig = <selene.core.configuration.Config object at 0x7ff7e625de90>\n\n    def _build_local_driver_by_name_or_remote_by_url_and_options(\n        config: Config,\n    ) -> WebDriver:\n        from selenium.webdriver import (\n            ChromeOptions,\n            EdgeOptions,\n            Chrome,\n            Firefox,\n            Edge,\n        )\n    \n        from selenium.webdriver.chrome.service import Service as ChromeService\n        from selenium.webdriver.firefox.service import Service as FirefoxService\n        from selenium.webdriver.edge.service import Service as EdgeService  # type: ignore\n    \n        from webdriver_manager.chrome import ChromeDriverManager  # type: ignore\n        from webdriver_manager.firefox import GeckoDriverManager  # type: ignore\n        from webdriver_manager.microsoft import EdgeChromiumDriverManager  # type: ignore\n    \n>       from webdriver_manager.core.utils import ChromeType  # type: ignore\nE       ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/webdriver_manager/core/utils.py)\n\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py:69: ImportError","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"browser_management","time":{"start":1697444620037,"stop":1697444620037,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"afterStages":[{"name":"browser_management::0","time":{"start":1697444620067,"stop":1697444620067,"duration":0},"status":"broken","statusMessage":"ImportError: cannot import name 'ChromeType' from 'webdriver_manager.core.utils' (/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/webdriver_manager/core/utils.py)\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"/home/runner/work/qa_guru_python_7/qa_guru_python_7/tests/conftest.py\", line 21, in browser_management\n    browser.quit()\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py\", line 1204, in quit\n    self.driver.quit()\n    ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/entity.py\", line 1099, in driver\n    return self.config.driver\n           ^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 345, in __get__\n    driver = config.build_driver_strategy(config)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/selene/core/configuration.py\", line 69, in _build_local_driver_by_name_or_remote_by_url_and_options\n    from webdriver_manager.core.utils import ChromeType  # type: ignore\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_selene"},{"name":"host","value":"fv-az398-616"},{"name":"thread","value":"2190-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_selene"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":1,"broken":3,"skipped":0,"passed":1,"unknown":0,"total":5},"items":[{"uid":"989b70b0033b5e6c","reportUrl":"https://vapolonov.github.io/qa_guru_python_7/9//#testresult/989b70b0033b5e6c","status":"failed","statusDetails":"selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('link text', 'eroshenkoam/allure-example')).click\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"link text\",\"selector\":\"eroshenkoam/allure-example\"}\n  (Session info: headless chrome=114.0.5735.198); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x562055d354e3 <unknown>\n#1 0x562055a64c76 <unknown>\n#2 0x562055aa0c96 <unknown>\n#3 0x562055aa0dc1 <unknown>\n#4 0x562055ada7f4 <unknown>\n#5 0x562055ac003d <unknown>\n#6 0x562055ad830e <unknown>\n#7 0x562055abfde3 <unknown>\n#8 0x562055a952dd <unknown>\n#9 0x562055a9634e <unknown>\n#10 0x562055cf53e4 <unknown>\n#11 0x562055cf93d7 <unknown>\n#12 0x562055d03b20 <unknown>\n#13 0x562055cfa023 <unknown>\n#14 0x562055cc81aa <unknown>\n#15 0x562055d1e6b8 <unknown>\n#16 0x562055d1e847 <unknown>\n#17 0x562055d2e243 <unknown>\n#18 0x7f4d6a0bab43 <unknown>\n\nScreenshot: file:///home/runner/.selene/screenshots/1688982498799/1688982498799.png\nPageSource: file:///home/runner/.selene/screenshots/1688982498799/1688982498799.html","time":{"start":1688982500824,"stop":1688982507546,"duration":6722}},{"uid":"92c122d0b9566dfd","reportUrl":"https://vapolonov.github.io/qa_guru_python_7/8//#testresult/92c122d0b9566dfd","status":"passed","time":{"start":1688981953120,"stop":1688981960225,"duration":7105}},{"uid":"7ac388af4e5df7fc","reportUrl":"https://vapolonov.github.io/qa_guru_python_7/7//#testresult/7ac388af4e5df7fc","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x56358b22f4e3 <unknown>\n#1 0x56358af5ec76 <unknown>\n#2 0x56358af87d78 <unknown>\n#3 0x56358af84029 <unknown>\n#4 0x56358afc2ccc <unknown>\n#5 0x56358afc247f <unknown>\n#6 0x56358afb9de3 <unknown>\n#7 0x56358af8f2dd <unknown>\n#8 0x56358af9034e <unknown>\n#9 0x56358b1ef3e4 <unknown>\n#10 0x56358b1f33d7 <unknown>\n#11 0x56358b1fdb20 <unknown>\n#12 0x56358b1f4023 <unknown>\n#13 0x56358b1c21aa <unknown>\n#14 0x56358b2186b8 <unknown>\n#15 0x56358b218847 <unknown>\n#16 0x56358b228243 <unknown>\n#17 0x7fbd97b3cb43 <unknown>","time":{"start":1688980172645,"stop":1688980173289,"duration":644}},{"uid":"4ff1187b2bae8427","reportUrl":"https://vapolonov.github.io/qa_guru_python_7/5//#testresult/4ff1187b2bae8427","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55e1ca2a54e3 <unknown>\n#1 0x55e1c9fd4c76 <unknown>\n#2 0x55e1c9ffdd78 <unknown>\n#3 0x55e1c9ffa029 <unknown>\n#4 0x55e1ca038ccc <unknown>\n#5 0x55e1ca03847f <unknown>\n#6 0x55e1ca02fde3 <unknown>\n#7 0x55e1ca0052dd <unknown>\n#8 0x55e1ca00634e <unknown>\n#9 0x55e1ca2653e4 <unknown>\n#10 0x55e1ca2693d7 <unknown>\n#11 0x55e1ca273b20 <unknown>\n#12 0x55e1ca26a023 <unknown>\n#13 0x55e1ca2381aa <unknown>\n#14 0x55e1ca28e6b8 <unknown>\n#15 0x55e1ca28e847 <unknown>\n#16 0x55e1ca29e243 <unknown>\n#17 0x7f0f37c35b43 <unknown>","time":{"start":1688978997939,"stop":1688978998583,"duration":644}}]},"tags":[]},"source":"4b81908effdddaf6.json","parameterValues":[]}